name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # --- S3 related steps are removed ---

      - name: SSH into EC2 and manage app with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory on EC2
            cd /home/ubuntu/my-messenger

            # Pull the latest code from the main branch
            git pull origin main

            # Install any new dependencies
            npm install

            # Build the Next.js application
            npm run build

            # Check if the PM2 process for 'my-messenger' exists
            pm2 describe my-messenger > /dev/null
            if [ $? -eq 0 ]; then
              # If it exists, restart the PM2 process
              pm2 restart my-messenger
            else
              # If not, start a new PM2 process for the Next.js app on port 3000
              pm2 start npm --name my-messenger -- run start -- -p 3000
              # Save the PM2 process list to restore on reboot
              pm2 save
            fi