name: Deploy to EC2 and S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload static assets to S3
        run: |
          aws s3 sync .next/static/ s3://my-messenger-assets-bucket/_next/static/ 
          aws s3 sync public/ s3://my-messenger-assets-bucket/ 

      - name: SSH into EC2 and manage app with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/my-messenger # Ensure this path is correct for your project
            git pull origin main
            npm install
            npm run build
            # Check if the PM2 process exists before trying to restart
            pm2 describe my-messenger > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart my-messenger
            else
              # If not, start a new PM2 process
              pm2 start npm --name my-messenger -- run start -- -p 3000
              pm2 save # Save the PM2 process list to restore on reboot
            fi